services:
  sbha-db:
    image: mysql:latest
    container_name: sbha-db
    ports:
      - "3306:3306"
    env_file: .env
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./sbha-db_data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: "./Dockerfile"
    container_name: app
    depends_on:
      - sbha-db
    ports:
      - "8000:8000"
    env_file: .env
    volumes:
      - ./app:/app


networks:
  sbha-network:
    driver: bridge